### ISSUE TITLE
Flytte twitterserveren fra lokal app.js til en vi setter opp

### ISSUE THREAD

**Issue by ewendel** [ewendel/react-workshop#1]
Folk får problemer med Twitter.

F.eks har de ikke Twitterkonto, sliter med å registrere telefonnummer eller at noe annet bugger.
Foreslår at vi server Twitterdata fra vår maskin, og heller hardkoder inn vår IP under workshopen i BCN.

**Comment by kimjoar** [comment]
Fikset i readme.
