### ISSUE TITLE
Remove large pdf from repo

### ISSUE THREAD

**Issue by carljoachim** [ewendel/react-workshop#5]
It would be great if the pdf presentation could be excluded from the master branch, so that the git clone repo could be a much smaller. Maybe put the tasks with the presentation in a seperate branch?

**Comment by kimjoar** [comment]
Agreed! Let's do that when we prepare the next presentation, @ewendel

**Comment by ewendel** [comment]
slides were removed long ago, but re-included this morning as @peterhemmen asked for them

**Comment by kjbekkelund** [comment]
Done
